import type {
  User,
  Workspace,
  Project,
  Issue,
  Discussion,
  FileItem,
  Notification,
  ActivityEvent,
  Label,
  DiscussionCategory,
  IssueStatus,
  Priority,
  ProjectStatus,
  UserRole,
  NotificationType,
} from "@/types";

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 86400000);
const hoursAgo = (hours: number) => new Date(now.getTime() - hours * 3600000);
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60000);

export const mockUsers: User[] = [
  {
    id: "usr_01",
    username: "abhipatel",
    displayName: "Abhi Patel",
    email: "abhi@forge.dev",
    avatarUrl: null,
    bio: "Full-stack engineer. Building developer tools that don't suck.",
    role: "owner",
    createdAt: daysAgo(180),
    lastActiveAt: minutesAgo(2),
    isOnline: true,
  },
  {
    id: "usr_02",
    username: "rahulsharma",
    displayName: "Rahul Sharma",
    email: "rahul@forge.dev",
    avatarUrl: null,
    bio: "Backend systems. Distributed. Opinionated.",
    role: "admin",
    createdAt: daysAgo(150),
    lastActiveAt: minutesAgo(15),
    isOnline: true,
  },
  {
    id: "usr_03",
    username: "priyasingh",
    displayName: "Priya Singh",
    email: "priya@forge.dev",
    avatarUrl: null,
    bio: "Frontend. Design systems. Accessibility enthusiast.",
    role: "member",
    createdAt: daysAgo(120),
    lastActiveAt: hoursAgo(1),
    isOnline: true,
  },
  {
    id: "usr_04",
    username: "amanpatel",
    displayName: "Aman Patel",
    email: "aman@forge.dev",
    avatarUrl: null,
    bio: "DevOps. Infrastructure. SRE.",
    role: "member",
    createdAt: daysAgo(90),
    lastActiveAt: hoursAgo(3),
    isOnline: false,
  },
  {
    id: "usr_05",
    username: "neha gupta",
    displayName: "Neha Gupta",
    email: "neha@forge.dev",
    avatarUrl: null,
    bio: "Product. Strategy. Former engineer.",
    role: "viewer",
    createdAt: daysAgo(60),
    lastActiveAt: daysAgo(1),
    isOnline: false,
  },
  {
    id: "usr_06",
    username: "vikramr",
    displayName: "Vikram Reddy",
    email: "vikram@forge.dev",
    avatarUrl: null,
    bio: "Mobile. React Native. Performance.",
    role: "member",
    createdAt: daysAgo(45),
    lastActiveAt: minutesAgo(30),
    isOnline: true,
  },
];

export const mockWorkspaces: Workspace[] = [
  {
    id: "ws_01",
    name: "Forge Core",
    description: "Main workspace for Forge platform development",
    slug: "forge-core",
    ownerId: "usr_01",
    memberCount: 6,
    projectCount: 4,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "ws_02",
    name: "Synapse",
    description: "Real-time collaboration engine",
    slug: "synapse",
    ownerId: "usr_02",
    memberCount: 4,
    projectCount: 2,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(2),
  },
];

export const mockProjects: Project[] = [
  {
    id: "proj_01",
    workspaceId: "ws_01",
    name: "Forge CLI",
    description: "Command-line interface for Forge workspace management and project scaffolding",
    key: "CLI",
    status: "active",
    progress: 68,
    memberCount: 3,
    issueCount: 24,
    openIssueCount: 8,
    createdAt: daysAgo(90),
    updatedAt: hoursAgo(2),
    ownerId: "usr_01",
  },
  {
    id: "proj_02",
    workspaceId: "ws_01",
    name: "TypeWithMe",
    description: "Real-time collaborative typing platform with operational transforms",
    key: "TWM",
    status: "active",
    progress: 45,
    memberCount: 4,
    issueCount: 31,
    openIssueCount: 14,
    createdAt: daysAgo(60),
    updatedAt: hoursAgo(1),
    ownerId: "usr_01",
  },
  {
    id: "proj_03",
    workspaceId: "ws_02",
    name: "Auth Overhaul",
    description: "Complete authentication system rewrite with OAuth2, SSO, and MFA support",
    key: "AUTH",
    status: "planning",
    progress: 15,
    memberCount: 2,
    issueCount: 12,
    openIssueCount: 10,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(3),
    ownerId: "usr_02",
  },
  {
    id: "proj_04",
    workspaceId: "ws_01",
    name: "Forge API",
    description: "RESTful API layer for all Forge platform operations",
    key: "API",
    status: "active",
    progress: 72,
    memberCount: 3,
    issueCount: 18,
    openIssueCount: 5,
    createdAt: daysAgo(120),
    updatedAt: hoursAgo(4),
    ownerId: "usr_02",
  },
];

export const mockLabels: Label[] = [
  { id: "lbl_01", projectId: "proj_02", name: "bug", color: "#ef4444", description: "Something isn't working" },
  { id: "lbl_02", projectId: "proj_02", name: "feature", color: "#22c55e", description: "New feature request" },
  { id: "lbl_03", projectId: "proj_02", name: "websocket", color: "#3b82f6", description: "WebSocket related" },
  { id: "lbl_04", projectId: "proj_02", name: "realtime", color: "#00d4aa", description: "Real-time functionality" },
  { id: "lbl_05", projectId: "proj_02", name: "performance", color: "#fbbf24", description: "Performance issues" },
  { id: "lbl_06", projectId: "proj_02", name: "documentation", color: "#a855f7", description: "Documentation updates" },
  { id: "lbl_07", projectId: "proj_01", name: "cli", color: "#3b82f6", description: "CLI related" },
  { id: "lbl_08", projectId: "proj_01", name: "scaffold", color: "#22c55e", description: "Project scaffolding" },
  { id: "lbl_09", projectId: "proj_03", name: "oauth", color: "#3b82f6", description: "OAuth implementation" },
  { id: "lbl_10", projectId: "proj_03", name: "security", color: "#ef4444", description: "Security concerns" },
];

export const mockIssues: Issue[] = [
  {
    id: "iss_01",
    projectId: "proj_02",
    number: 42,
    title: "WebSocket reconnect fails after network loss",
    description: "When the network connection is lost and restored, the WebSocket client fails to reconnect properly. The client enters a retry loop but never establishes a new connection.\n\n**Steps to reproduce:**\n1. Start a typing session\n2. Disable network adapter\n3. Wait 30 seconds\n4. Re-enable network adapter\n5. Observe connection status stays 'disconnected'\n\n**Expected:** Automatic reconnection within 5 seconds\n**Actual:** Permanent disconnection requiring page reload",
    status: "in_progress",
    priority: "high",
    assigneeId: "usr_01",
    reporterId: "usr_02",
    labels: [mockLabels[2], mockLabels[3]],
    commentsCount: 8,
    attachmentsCount: 2,
    dueDate: daysAgo(-2),
    startedAt: daysAgo(1),
    completedAt: null,
    createdAt: daysAgo(3),
    updatedAt: hoursAgo(2),
  },
  {
    id: "iss_02",
    projectId: "proj_02",
    number: 41,
    title: "Cursor position drift during rapid typing",
    description: "Multiple users typing simultaneously causes cursor positions to drift apart over time. After approximately 2 minutes of rapid concurrent editing, cursors are offset by 2-3 characters.",
    status: "review",
    priority: "medium",
    assigneeId: "usr_03",
    reporterId: "usr_01",
    labels: [mockLabels[3], mockLabels[4]],
    commentsCount: 5,
    attachmentsCount: 1,
    dueDate: null,
    startedAt: daysAgo(4),
    completedAt: null,
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(4),
  },
  {
    id: "iss_03",
    projectId: "proj_02",
    number: 40,
    title: "Add operational transform conflict resolution",
    description: "Implement OT algorithm for handling concurrent text edits. Need to support both character-level and block-level transformations.",
    status: "backlog",
    priority: "high",
    assigneeId: null,
    reporterId: "usr_01",
    labels: [mockLabels[3]],
    commentsCount: 12,
    attachmentsCount: 0,
    dueDate: daysAgo(-7),
    startedAt: null,
    completedAt: null,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
  },
  {
    id: "iss_04",
    projectId: "proj_02",
    number: 39,
    title: "Memory leak in document sync service",
    description: "The document synchronization service accumulates memory over time. After running for 24 hours with 50 concurrent connections, memory usage grows from 256MB to 1.2GB.",
    status: "done",
    priority: "critical",
    assigneeId: "usr_02",
    reporterId: "usr_04",
    labels: [mockLabels[4], mockLabels[0]],
    commentsCount: 6,
    attachmentsCount: 3,
    dueDate: daysAgo(1),
    startedAt: daysAgo(5),
    completedAt: daysAgo(1),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
  {
    id: "iss_05",
    projectId: "proj_02",
    number: 38,
    title: "Implement user presence indicators",
    description: "Show real-time online/offline status for all workspace members. Include typing indicators in document views.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "usr_03",
    reporterId: "usr_01",
    labels: [mockLabels[3]],
    commentsCount: 4,
    attachmentsCount: 0,
    dueDate: daysAgo(-3),
    startedAt: daysAgo(2),
    completedAt: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
  },
  {
    id: "iss_06",
    projectId: "proj_01",
    number: 15,
    title: "Add workspace scaffolding command",
    description: "Create 'forge init' command that generates a new workspace with standard configuration files, directory structure, and initial project setup.",
    status: "in_progress",
    priority: "high",
    assigneeId: "usr_01",
    reporterId: "usr_02",
    labels: [mockLabels[6], mockLabels[7]],
    commentsCount: 3,
    attachmentsCount: 1,
    dueDate: daysAgo(-1),
    startedAt: daysAgo(3),
    completedAt: null,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
  {
    id: "iss_07",
    projectId: "proj_01",
    number: 14,
    title: "Fix Windows path resolution in project generator",
    description: "The project generator fails on Windows when paths contain spaces or special characters. Need to normalize paths before file operations.",
    status: "review",
    priority: "high",
    assigneeId: "usr_04",
    reporterId: "usr_01",
    labels: [mockLabels[6], mockLabels[0]],
    commentsCount: 7,
    attachmentsCount: 2,
    dueDate: null,
    startedAt: daysAgo(4),
    completedAt: null,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(4),
  },
  {
    id: "iss_08",
    projectId: "proj_03",
    number: 8,
    title: "Design OAuth2 flow architecture",
    description: "Create architecture document for OAuth2 implementation supporting Google, GitHub, and custom OIDC providers. Include token refresh strategy.",
    status: "backlog",
    priority: "medium",
    assigneeId: null,
    reporterId: "usr_02",
    labels: [mockLabels[8], mockLabels[9]],
    commentsCount: 9,
    attachmentsCount: 1,
    dueDate: daysAgo(-10),
    startedAt: null,
    completedAt: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
  },
];

export const mockDiscussions: Discussion[] = [
  {
    id: "disc_01",
    projectId: "proj_02",
    workspaceId: "ws_01",
    category: "technical",
    title: "Should Forge use PostgreSQL full-text search or Elasticsearch?",
    content: "We're debating between PostgreSQL's built-in full-text search and spinning up Elasticsearch. PostgreSQL would reduce operational complexity but Elasticsearch offers better query flexibility and performance at scale.\n\n**PostgreSQL pros:**\n- No additional infrastructure\n- ACID compliance\n- Simpler deployment\n\n**Elasticsearch pros:**\n- Better search relevance\n- Faceted search built-in\n- Handles high query volume\n\nWhat's the team's experience with both?",
    authorId: "usr_01",
    repliesCount: 14,
    viewsCount: 89,
    isPinned: true,
    isLocked: false,
    lastActivityAt: hoursAgo(3),
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(3),
    tags: ["architecture", "search", "postgresql"],
  },
  {
    id: "disc_02",
    projectId: null,
    workspaceId: "ws_01",
    category: "proposal",
    title: "RFC: Adopting TypeScript strict mode across all projects",
    content: "I propose we enable TypeScript strict mode for all Forge projects. This would catch more bugs at compile time and improve code quality.\n\nCurrently, only the API project uses strict mode. Enabling it across CLI, TypeWithMe, and the web client would require some refactoring but would pay dividends.\n\nThoughts?",
    authorId: "usr_03",
    repliesCount: 8,
    viewsCount: 56,
    isPinned: false,
    isLocked: false,
    lastActivityAt: daysAgo(1),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    tags: ["typescript", "code-quality", "rfc"],
  },
  {
    id: "disc_03",
    projectId: "proj_01",
    workspaceId: "ws_01",
    category: "technical",
    title: "CLI plugin architecture for extensibility",
    content: "Let's discuss how to make Forge CLI extensible through plugins. We need a clear interface for third-party developers to add commands and extend functionality.",
    authorId: "usr_02",
    repliesCount: 6,
    viewsCount: 42,
    isPinned: false,
    isLocked: false,
    lastActivityAt: daysAgo(2),
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
    tags: ["cli", "plugins", "architecture"],
  },
  {
    id: "disc_04",
    projectId: null,
    workspaceId: "ws_01",
    category: "announcement",
    title: "Sprint planning: Q2 priorities finalized",
    content: "The Q2 sprint planning is complete. Key priorities:\n\n1. TypeWithMe beta launch\n2. Authentication overhaul Phase 1\n3. Forge CLI public release\n4. Performance optimization pass\n\nFull breakdown in the attached document.",
    authorId: "usr_01",
    repliesCount: 3,
    viewsCount: 112,
    isPinned: true,
    isLocked: false,
    lastActivityAt: daysAgo(3),
    createdAt: daysAgo(4),
    updatedAt: daysAgo(3),
    tags: ["planning", "sprint", "announcement"],
  },
];

export const mockFiles: FileItem[] = [
  {
    id: "file_01",
    projectId: "proj_02",
    workspaceId: "ws_01",
    name: "architecture.md",
    path: "docs/architecture.md",
    type: "file",
    mimeType: "text/markdown",
    size: 24576,
    uploadedById: "usr_01",
    version: 3,
    parentId: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "file_02",
    projectId: "proj_02",
    workspaceId: "ws_01",
    name: "Documents",
    path: "Documents",
    type: "folder",
    mimeType: null,
    size: 0,
    uploadedById: "usr_01",
    version: 1,
    parentId: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(10),
  },
  {
    id: "file_03",
    projectId: "proj_02",
    workspaceId: "ws_01",
    name: "Design",
    path: "Design",
    type: "folder",
    mimeType: null,
    size: 0,
    uploadedById: "usr_03",
    version: 1,
    parentId: null,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(8),
  },
  {
    id: "file_04",
    projectId: "proj_02",
    workspaceId: "ws_01",
    name: "wireframes-v2.fig",
    path: "Design/wireframes-v2.fig",
    type: "file",
    mimeType: "application/octet-stream",
    size: 15728640,
    uploadedById: "usr_03",
    version: 2,
    parentId: "file_03",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(3),
  },
  {
    id: "file_05",
    projectId: "proj_02",
    workspaceId: "ws_01",
    name: "api-spec.yaml",
    path: "docs/api-spec.yaml",
    type: "file",
    mimeType: "text/yaml",
    size: 45056,
    uploadedById: "usr_02",
    version: 7,
    parentId: null,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "file_06",
    projectId: "proj_02",
    workspaceId: "ws_01",
    name: "performance-report.pdf",
    path: "Attachments/performance-report.pdf",
    type: "file",
    mimeType: "application/pdf",
    size: 2097152,
    uploadedById: "usr_04",
    version: 1,
    parentId: null,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
  },
  {
    id: "file_07",
    projectId: "proj_01",
    workspaceId: "ws_01",
    name: "README.md",
    path: "README.md",
    type: "file",
    mimeType: "text/markdown",
    size: 8192,
    uploadedById: "usr_01",
    version: 5,
    parentId: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif_01",
    userId: "usr_01",
    type: "mention",
    title: "Rahul mentioned you in a discussion",
    message: "in 'Should Forge use PostgreSQL full-text search?'",
    actionUrl: "/workspaces/ws_01/projects/proj_02/discussions",
    metadata: { discussionId: "disc_01", userId: "usr_02" },
    isRead: false,
    createdAt: hoursAgo(1),
  },
  {
    id: "notif_02",
    userId: "usr_01",
    type: "assignment",
    title: "New issue assigned to you",
    message: "Issue #42: WebSocket reconnect fails after network loss",
    actionUrl: "/workspaces/ws_01/projects/proj_02/issues/iss_01",
    metadata: { issueId: "iss_01", projectId: "proj_02" },
    isRead: false,
    createdAt: hoursAgo(2),
  },
  {
    id: "notif_03",
    userId: "usr_01",
    type: "comment",
    title: "Priya commented on Issue #41",
    message: "I've pushed a fix for the cursor drift issue. Ready for review.",
    actionUrl: "/workspaces/ws_01/projects/proj_02/issues/iss_02",
    metadata: { issueId: "iss_02", userId: "usr_03" },
    isRead: false,
    createdAt: hoursAgo(4),
  },
  {
    id: "notif_04",
    userId: "usr_01",
    type: "project_activity",
    title: "Forge CLI build passed",
    message: "All 142 tests passed. Coverage: 87%",
    actionUrl: "/workspaces/ws_01/projects/proj_01",
    metadata: { projectId: "proj_01" },
    isRead: true,
    createdAt: hoursAgo(6),
  },
  {
    id: "notif_05",
    userId: "usr_01",
    type: "workspace_invite",
    title: "Neha joined Forge Core",
    message: "Neha Gupta has been added as a Viewer",
    actionUrl: "/workspaces/ws_01/team",
    metadata: { userId: "usr_05", workspaceId: "ws_01" },
    isRead: true,
    createdAt: daysAgo(1),
  },
  {
    id: "notif_06",
    userId: "usr_01",
    type: "system",
    title: "Forge API deployment completed",
    message: "Version 2.4.1 deployed to production",
    actionUrl: "/workspaces/ws_01/projects/proj_04",
    metadata: { projectId: "proj_04", version: "2.4.1" },
    isRead: true,
    createdAt: daysAgo(2),
  },
];

export const mockActivities: ActivityEvent[] = [
  {
    id: "act_01",
    workspaceId: "ws_01",
    projectId: "proj_02",
    userId: "usr_01",
    type: "issue_created",
    description: "created Issue #42",
    metadata: { issueNumber: 42, issueTitle: "WebSocket reconnect fails after network loss" },
    createdAt: daysAgo(3),
  },
  {
    id: "act_02",
    workspaceId: "ws_01",
    projectId: "proj_02",
    userId: "usr_02",
    type: "issue_moved",
    description: "moved 'Redis integration' to Done",
    metadata: { issueNumber: 39, from: "review", to: "done" },
    createdAt: daysAgo(1),
  },
  {
    id: "act_03",
    workspaceId: "ws_01",
    projectId: "proj_02",
    userId: "usr_03",
    type: "comment",
    description: "commented on Issue #41",
    metadata: { issueNumber: 41 },
    createdAt: hoursAgo(4),
  },
  {
    id: "act_04",
    workspaceId: "ws_01",
    projectId: "proj_01",
    userId: "usr_04",
    type: "member_joined",
    description: "joined Forge CLI",
    metadata: { projectName: "Forge CLI" },
    createdAt: daysAgo(5),
  },
  {
    id: "act_05",
    workspaceId: "ws_01",
    projectId: null,
    userId: "usr_01",
    type: "project_created",
    description: "created project 'Auth Overhaul'",
    metadata: { projectId: "proj_03", projectName: "Auth Overhaul" },
    createdAt: daysAgo(30),
  },
  {
    id: "act_06",
    workspaceId: "ws_01",
    projectId: "proj_02",
    userId: "usr_02",
    type: "pull_request",
    description: "opened PR #87 for 'Memory leak fix'",
    metadata: { prNumber: 87, prTitle: "Memory leak fix" },
    createdAt: daysAgo(2),
  },
];

export function getUserById(id: string): User | undefined {
  return mockUsers.find((u) => u.id === id);
}

export function getWorkspaceById(id: string): Workspace | undefined {
  return mockWorkspaces.find((w) => w.id === id);
}

export function getProjectById(id: string): Project | undefined {
  return mockProjects.find((p) => p.id === id);
}

export function getIssueById(id: string): Issue | undefined {
  return mockIssues.find((i) => i.id === id);
}

export function getDiscussionById(id: string): Discussion | undefined {
  return mockDiscussions.find((d) => d.id === id);
}

export function getFileById(id: string): FileItem | undefined {
  return mockFiles.find((f) => f.id === id);
}

export function getNotificationsByUser(userId: string): Notification[] {
  return mockNotifications.filter((n) => n.userId === userId);
}

export function getIssuesByProject(projectId: string): Issue[] {
  return mockIssues.filter((i) => i.projectId === projectId);
}

export function getDiscussionsByProject(projectId: string): Discussion[] {
  return mockDiscussions.filter((d) => d.projectId === projectId);
}

export function getFilesByProject(projectId: string): FileItem[] {
  return mockFiles.filter((f) => f.projectId === projectId);
}

export function getActivitiesByWorkspace(workspaceId: string): ActivityEvent[] {
  return mockActivities.filter((a) => a.workspaceId === workspaceId);
}